### ISSUE TITLE
IntelliJ IDEA 2024.3.1 RC 版本无法运行

### ISSUE THREAD

**Issue by weirdo-adam** [lin2j/simple-deployment#18]
IntelliJ IDEA 2024.3.1 RC (Ultimate Edition)

Unhandled exception in [ComponentManager(ProjectImpl@248127315), com.intellij.codeWithMe.ClientIdContextElementPrecursor@308cb56a, CoroutineName(com.intellij.openapi.wm.impl.ToolWindowManagerImpl), Dispatchers.Default]

java.lang.NullPointerException: Cannot invoke "tech.lin2j.idea.plugin.model.ConfigPersistence.getServerTags()" because "tech.lin2j.idea.plugin.model.ConfigHelper.CONFIG_PERSISTENCE" is null
	at tech.lin2j.idea.plugin.model.ConfigHelper.getServerTags(ConfigHelper.java:164)
	at tech.lin2j.idea.plugin.ui.DashboardView.refreshTagComboBox(DashboardView.java:123)
	at tech.lin2j.idea.plugin.ui.DashboardView.initTagComboBox(DashboardView.java:117)
	at tech.lin2j.idea.plugin.ui.DashboardView.initToolbar(DashboardView.java:74)
	at tech.lin2j.idea.plugin.ui.DashboardView.<init>(DashboardView.java:61)
	at tech.lin2j.idea.plugin.module.DeployConsoleView.<init>(DeployConsoleView.java:20)
	at tech.lin2j.idea.plugin.factory.DeployConsoleToolWindowFactory.createToolWindowContent(DeployConsoleToolWindowFactory.java:25)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:689)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:669)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1058)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:992)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:973)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$lambda$34(ToolWindowManagerImpl.kt:1193)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1206)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1089)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$initToolWindow$3.invokeSuspend(ToolWindowManagerImpl.kt:582)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:44)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [ComponentManager(ProjectImpl@248127315), com.intellij.codeWithMe.ClientIdContextElementPrecursor@308cb56a, CoroutineName(com.intellij.openapi.wm.impl.ToolWindowManagerImpl), StandaloneCoroutine{Cancelled}@dbd2e4f, Dispatchers.Default]

**Comment by gziqt** [comment]
同样的问题

**Comment by lin2j** [comment]
我装了个 IDEA 2024.3.1 RC 版本的测了一下，没有发生这个问题。你这个是在插件中心装完之后就会报错吗？

"tech.lin2j.idea.plugin.model.ConfigHelper.CONFIG_PERSISTENCE"  我代码里关于这个配置文件的用法是错误的，准备找个时间重构一下这一块代码的

**Comment by lin2j** [comment]
"tech.lin2j.idea.plugin.model.ConfigHelper.CONFIG_PERSISTENCE"  我代码里关于这个配置文件的用法是错误的，准备找个时间重构一下这一块代码的

**Comment by weirdo-adam** [comment]
是的发自我的 iPhone在 2024年12月3日，21:15，Kenny ***@***.***> 写道：﻿
我装了个 IDEA 2024.3.1 RC 版本的测了一下，没有发生这个问题。你这个是在插件中心装完之后就会报错吗？

**Comment by weirdo-adam** [comment]
﻿﻿是的在 2024年12月3日，21:15，Kenny ***@***.***> 写道：﻿
我装了个 IDEA 2024.3.1 RC 版本的测了一下，没有发生这个问题。你这个是在插件中心装完之后就会报错吗？
